'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.18408
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Projeto_Sistema_de_Hotel.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4queijos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4queijos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlhoeOLEO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlhoeOLEO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alicci() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alicci", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almoço1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almoço1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almoço2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almoço2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almoço3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almoço3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almoço4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almoço4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ALmoço5FrutosMar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ALmoço5FrutosMar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almoço7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almoço7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlmoçoFrutosMAr6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlmoçoFrutosMAr6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property americana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("americana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bacon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bacon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Baiana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Baiana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Brcolis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brcolis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property burguersimples() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("burguersimples", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CababresaCATUPIRI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CababresaCATUPIRI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cachorroCOROA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cachorroCOROA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CafeComum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeComum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CafeComumDesenhado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeComumDesenhado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CafeFamilia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CafeFamilia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalabreaMineira() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalabreaMineira", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CalabrezaCHEDAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalabrezaCHEDAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CamaraoAparte2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CamaraoAparte2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Camponesa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Camponesa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cardapio_chalkboard_lousa_quadro_negro_D_NQ_NP_668778_MLB28225011390_092018_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cardapio_chalkboard_lousa_quadro_negro_D_NQ_NP_668778_MLB28225011390_092018_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property catupiry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("catupiry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property champgnon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("champgnon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comboburguer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comboburguer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comprimido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comprimido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comprimidoderrubado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comprimidoderrubado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property creches_para_cachorro_cover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creches_para_cachorro_cover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crocante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crocante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property D_NP_608869_MLB28225023243_092018_Q() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D_NP_608869_MLB28225023243_092018_Q", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dog_in_shopping_cart_with_toys_850x600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dog_in_shopping_cart_with_toys_850x600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Editada1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editada1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editadadeficiente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editadadeficiente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EditadaExclusivoClientes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditadaExclusivoClientes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EditadaMoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EditadaMoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Escarola() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Escarola", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EspeciariasemCAFÈ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EspeciariasemCAFÈ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property essa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("essa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property este() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("este", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filhoteremedio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filhoteremedio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FrangoCaipira() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrangoCaipira", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FrangoCATUPIRI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrangoCATUPIRI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FrangoChedar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FrangoChedar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gorgonzola() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gorgonzola", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grega() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grega", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hamburguer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hamburguer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Havaiana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Havaiana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Humita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Humita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Importados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Importados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property índice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("índice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Injetaveis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Injetaveis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jantar5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jantar5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jantar7_almondegas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jantar7_almondegas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jantarcozido_marroquino_com_quinoa_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jantarcozido_marroquino_com_quinoa_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jantargrao_de_bico_com_frango_e_legumes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jantargrao_de_bico_com_frango_e_legumes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jantarMacarraoCamaraoTomate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jantarMacarraoCamaraoTomate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JantarMacarraoCarneRucula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JantarMacarraoCarneRucula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property JantarPanquecas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JantarPanquecas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kingburguer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kingburguer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Limpeza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Limpeza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property liquido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liquido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Livre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Livre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lombo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lombo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LomboCalifornia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LomboCalifornia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LomboCanadense() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LomboCanadense", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LomboCatupiry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LomboCatupiry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Madalena() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Madalena", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Margarita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Margarita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Marguerita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Marguerita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_poster_chalkboard_30x40_menu_06_D_NQ_NP_773152_MLB26339338033_112017_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_poster_chalkboard_30x40_menu_06_D_NQ_NP_773152_MLB26339338033_112017_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mexicana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mexicana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MilhoVERDE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MilhoVERDE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MotoDisponivel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MotoDisponivel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MotoProibidoEstacionar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MotoProibidoEstacionar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mussarela() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mussarela", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property naopagocomanda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("naopagocomanda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property napolitana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("napolitana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Oculpado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Oculpado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pet2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pet2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pet3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pet3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pet4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pet4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pet5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pet5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pet6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pet6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property petatual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("petatual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property petprincipal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("petprincipal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property petprincipal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("petprincipal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property petprincpaltop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("petprincpaltop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Portuguesa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portuguesa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property principalmedicamentos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("principalmedicamentos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Provolone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Provolone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VagaDisponivel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VagaDisponivel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VagaOculpada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VagaOculpada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vegetariana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vegetariana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
